export const projectsList = [
    'Blackout',
    'Booking',
    'Ashes of Creation',
    'Terminus',
    'CareerBuilder',
    'Zuora',
    'Dollar Street',
    'Liberty Flights',
    'Souqalmal',
    'Priceshredder',
    'Gapminder Offline',
    'TablesReady',
    'Breethe',
    'StackBlitz',
    'Renaizant',
    'Cinnabon',
    'NgTalks',
    'Qualtrax',
    'ThisDot',
    'NgAtlanta',
    'Vizabi',
    'Netifi'
];
