The latitudes and longitudes won't get on our way - open source is boundless and
big-hearted. Thanks to Hacktoberfest, we can unite, buddy up, and even get treated for loving open source.

We at Valor Software are proud to be a part of the Angular community, and bring up https://valor-software.com/ngx-bootstrap/#/хngx-bootstrap:ъ for Hacktoberfest's challenges.

== How can I participate?

* Sign up to https://github.com/[GitHub^] if you don't have an account.
* Sign up on the https://hacktoberfest.digitalocean.com[Hacktoberfest site^] at any time between October 1 and October 31.
* Make pull requests to https://github.com/valor-software/ngx-bootstrap/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest[issues
tagged with "Hacktoberfest"label in ngx-bootstrap repo^] during October.
* Wait for your special edition Hacktoberfest swag from Valor Software.
* Enjoy being an open-source buddy!

== Contributing to open source...Sounds pretty cozy to me.

You don't need to be a super experienced developer to take part in Hacktoberfest. You use open source for sure (that's why you're here, actually). Why not try improving it yourself then? Every contribution makes the open source and yourself better.

== Are there any rules on pull requests?

You don't need to reinvent the wheel, but fixing minor typos in documentation is not the intent. Your change must be reasonable. Even if your pull request isn't accepted at the end, your time and help will be appreciated.

== So, Hacktoberfest swag - what are the gifts?

We've prepared some nice staff for you:

* For *one* pull request, you get a pen and a sticker.
* For *three* - a notepad or a wooden phone stand.
* For *five* - a full kit is yours! A pen, a sticker. a notepad, and a wooden phone
stand.

If you live in Kharkov, you'll get some sweets too )

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5d91e2dd4a0f1c21c1926af7_kz-lK5fm2CcE0VGpreZj4UUOYw_-9r4ROFqU_WOmi5LEpBmRcF2Ax7BnBfCaxnlVMy9yj2dK0OuvQM9BKNQGzA2-eDQ8jO3joJpFAuEHvDtE26tYAzn8kZHY8Yb8IaaDnSNDdinF.jpeg[]

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5d91e2ddbc81e32fb3e0380b_RouzTqU99ipGZthlSnjHmih9bTrnQRrfA9_UdXbl9oWCb6hJgIlFZJVRrl0yL4y7Q0ncsMOtCnWJZv0m2SNp1ImWHp0KPdWj8md6Zz5YN155AAW3L_m29DDuAv566qXK6y2VHMQ4.jpeg[]

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5d91e2ddd7ccc682175962ea_f27J06AkBW3Dd3pB4fanZWw1sbrhcs-GJCI5H3DgSK_U2R2cbRSAY_-3hTCe75DQU9iMPJpWnJJlSLra_yAyKtPmzmyeUlGVIVlTj2do6t_Y1za0aYfDaTVc8bR6yFgEwNIQ1ZXM.jpeg[]

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5d91e2dde6b25800bd2cb938_HzA39vKZa4R59B7CU-w4NXuLeiGYiiVztK34IXE4r-hVcWPU2WBF2sBi7-7GFaC3g1GcYHiOxqJ4_wLO1OZ_1v9dOaMwNjY8KNVLUjmEe29KPJqyTZfDOCUl3fW-GLql2XeIh2QK.jpeg[]

Happy Hacktoberfest-ing!
