A flat-structured company we're going to talk about is us, your humble servant, Valor
Software. In thisarticle, we want to share with you our direct experience in building a continuous growth system based on a toolcalled Career Path and implementing it in both our company and Renaizant - the app we developed.
But let'sstart with the backstory of why we decided to delve into building the career growth management
system.

We're still a growing company of less than 100 employees but have the ambition to be
proactive and want toescape https://www.mgtsystems.com/growing-pains[growing pains^],
especially related to ourmain value-people and their development:

1. We started with a focus on http://www.reinventingorganizationswiki.com/Teal_Organizations[the
teal^] organizational structure, the flattest one. Such a structure implies the absence of a job
hierarchy: we are all one team, and we flexibly unite to solve work tasks. However, even in the flattest
structure, employees have different levels of expertise and sets of soft skills, and should be able to
handle tasks of varying complexity. The process of choosing the most suitable performer for each role
becamean issue.

2. A certain gap was found between continuous development and the lack of monitoring tools and rewards for professional growth. In other words, our compensation system didn't look like a system that transparently links the growth of expertise with salary growth.

3. In time, it became apparent that we need to coordinate the directions of individual growth with the goals and needs of the organization: the company is ready to invest in the knowledge that is demanded by business. For this, we need to somehow formulate and convey to our employees our expectations.

4. We prefer to pick employees for new roles internally, rather than spending time and money to hire ones from the labor market. Thus, we needed to keep the number of open positions transparent for employees. Besides, in this case, employees can consider trending jobs first.

While the company is small (up to 50 employees), you can try to manage these issues "manually",
with everything in plain sight. With the growth of the organization, there's an increasing need for some kind of objective tool which will help you speed up and refine the processes.

We consider the emerging challenges as a call to create a "dashboard" available to all members of the organization while keeping the beloved teal approach. Let's see how it can be done.

== How to apply Career Path for a small-sized company. Our experience

We started to work in this direction four years ago. First, we introduced the practice of regular PerformanceReviews with the main focus on the employees' development. With
each employee, we agree on goals for the upcoming period, usually a half a year, and discuss a review of their compensation, taking into account the achievement of these goals. In parallel, from review to review, we formed and filled in our Competency Matrix,which describes our actual technological stack. However, these tools were rather isolated, cumbersome to use,and, most importantly, they didn't give us a clear visual picture as a result.

We wanted to have a tool to help each employee simulate their career path in
the organization and get a road map of movement along this path in a few clicks. We needed a tool that
combines a system of bands and grades with aCompetency Matrix. And, since we didn't find such existing tools on the market, we decided to create it ourselves :)

For starters, we grouped all available and planned positions "from top to bottom":

* Firstly, in *career tracks* - directions an employee can move a career in. Usually, companies
apply at least two career tracks-managerial and individual contributor.
* Then, in *job families* - according to the field of work and core responsibilities: HR and
recruiters as part of HR and so on.&nbsp
* Within each function, we positioned jobs sequentially according to the level of expertise like a trainee, junior, middle, senior to form *bands* - ranges of compensation given to groupings of
jobs. +
_As expected, the chains of jobs turned out to be of different lengths: for example,
for the CEO, there is no concept of "trainee", and the QA chain ends at the Lead level._

* Next, we determined *grades* - the mediate points within each band, providing a variety of
seniority sublevels. For example, grades for middle level could be Middle-, Middle, Middle+.

Then we needed to put everything in one system. How could we put different-type positions from all job
families together? Of course, we used the data from the labor market. Also, we referred to the point job evaluation method to rank and order all jobs considering the specifics of all jobs in our company.

The point method helped to dig deeper into the job evaluation. When using this method, the content of jobs can be described in terms of the key qualities of a job. Each factor is assigned points according to the extent to which that particular factor is presented in the job. The more points you assign to a job, the more worth the job has to the organization, thus, compensated more. There may be a group of factors for all jobs, various jobs separately, or a combination of company wide and position-specific factors. The most popular point method is https://en.wikipedia.org/wiki/Hay_Guide_Chart[the Hay system].

Having evaluated the jobs, we placed all the chains in a single table:

._An example of presenting a company's hierarchy when jobs are grouped into career tracks and job families and positioned according to bands &amp grades classification_.
[caption='']
image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5e9571b719faa77fab57695c_yAHtJUenv-xEkt6sxGtlmEwVffUsez8JbxwVB_qPxMxKl8rD2Xg_yih0vpTd1MzEiWW5fnxNBRdEBigQraLFqRoO4HyY0Wd0MPw7qWoh25qjVCmtnTf3iWB3Q7L3_RvGidKG5MGG.png[]

As a result, we got a "skeleton" of our system in the form of bands and grades.

The system of bands and grades is mainly used to manage compensation. For now, we leave this aspect beyond the Renaizant functionality and focus on our goal-using Renaizant to manage development and career.

The next step was adding the info on the required experience and open seats for each job, so each employee could see their place in the overall picture, along with the nearest available positions and a possible endpoint to visualize their career.

._Adding more details to let employees find the right next role for them: info on each job and potential next positions._
[caption='']
image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5e9571b8b0a7137b6ee70f29_qLKO7fGfJxdSx7D1gaJXDAKLCthFfTkYzdTu2DZjru8UrEBHWWiZONMGr-GjuyUxTgfQ7lKCQOFEl2aaOLdXJeGIQuvD-3VWdJVAt1e-K1jeVttq6YbQ7avHBOyhD7b7a8VW7OYh.png[]

Finally, for now, we identified and attached the required skills to each position. Now, this is
not justa linear diagram but a full-fledged roadmap showing:

* *Point A*. The starting point-employee's current position with an assessment of their
skills and skills for this position.

* *Point B*. The closest logical position-the next position within the current job family and
the assessment of employee's readiness to occupy it.

* *Point C*. Any desired position along with the required skills and the ability to assess
there adiness for this position. Keep in mind that the point C shouldn't necessarily be in the same row
as point A meaning a vertical career growth. There may be horizontal growth, which implies exploring
related fields staying in the current position but earning more, and multi-skilling, training in multiple skill-sets to perform two or more traditionally separate job functions, development.

._Eventually! Summary of employee's career path: the current, next, and desired positions, along with the corresponding skill assessments._
[caption='']
image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/5e9571b8b13e2d576ef04029_QMyO5RBecD097ucdWYXEXzxTib02_9uSofGlISsGdHfnHsRQt3fNEdQwComdS_ilhxwQtHXU4zi-FfHh-v_QtXW0rjEVfdDLE7N7vyEYz8_bqzjUkxm-01rQ2vxEqg6vv2IuC-FU.png[]

Now that employees plan their career path, they can see who has their desired position and ask
the secolleagues for information and advice, find out what goals they set for improving skills, how long it took, who was their mentor, and so on.

== What do we have as a result?

While small and medium-sized companies (up to 250 employees) may still try to juggle processes (but shouldn't!), for big companies it's even more crucial to automate the processes. Automatization tools can't replace humans in making decisions but can help you gather the required information and assist everyone in the company: employees, managers, HR, and even CEOs.

It's only the beginning of our automatization path. We haven't measured the satisfaction with update dprocesses yet but we do see the directions to track profit for every role:

*Employees can*:

* Visualize the job hierarchy and their current position in it.
* Involve an employee in their structured and regular development: offer education, help them to plan and visualize their career opportunities and direction that follow the needs and experience of the
organization.
* Find people who can help them to gain the necessary experience.

*Managers can:*

* Observe the level of professionalism of their teams
* Identify employees who asked for promotion and provide help, coaching, and mentorship for them
* Find the most experienced employees to help with internal education
* Find the most suitable internal candidates to take open vacancies.

*HR can:*

* Assess the speed of promotion in the organization
* Analyze staffing levels
* Group employees by desired positions and levels to organize bulk education
* Make the promotion process transparent and accessible for all employees
* Prevent demotivation and decreases in employee productivity because of getting stuck in the same position and not understanding career opportunities within the organization.

*CEO can:*

* Have eyes on general staffing situation of the company and the number of open seats
* Keep track of the number of employees in the company in total and per job family and position separately
* See the level of compliance of employees with their positions.

You likely started a similar journey earlier than us, and your organization already has an established
hierarchyof positions and associated tools. Then you just need to dust them off and improve your flow :) We hope our tool will make your journey smoother and welcome you to managing your company's Career Path with https://app.renaizant.com/[Renaizant^].

Stay tuned!


