Almost every movie place in our city offers an app to search for movies and buy tickets. So, you need to use several apps in parallel, you lose time comparing movie sessions and prices to make
the right choice. My task was to fix this and make this movie escape easy and convenient. I thought of one and only app that would display all the movie places and movies available. It would also allow for picking the movie from all the possible options in the city and purchasing them online.

In this article, I'll share how to design an app and lead you through every stage from user research to mock-up. Learn how to gather the information you need and create a splashing design based on users' pains and preferences. And, good luck with your beginnings :)

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6a92141388b7d2d9fe1_rOQ11ZZYkhE9Vg2brc3x94XaGdOQOuxUr6UbDK_Q2_RGn3JMBmOr_xGuJ6P2qaFQUh09hjAIfy8V9cs9NuBontVyETUHEFCY7Vnlaj5_Xd5pIrzmtDIUQRDVQxDm5U3uVyvn5V_o.png[]

== *Stage 1: Designing the product*

I attended the https://ux-clan.org/training/[Digital Product Design^] course, and my
graduation task was to develop a mobile app that would merge all the movie places of all the biggest Ukrainian cities. This app will ease finding a film, movie session, best seats, and buying tickets. I went with the iOS platform for the app.

==== *Business goal*

Sell movie tickets online

==== *Business requirements:*

. Users have an opportunity to pick films according to the genre, prices, location of a movie place, movie session time, seats available, etc.
. Users have an opportunity for online ticket purchases.

==== *Target audience research and analysis*

People of 18 - 35 who attend movies a couple times a month due to the pandemic made up my target audience. They use smartphones and the Internet widely, and most of them work in the office.

In my research I applied the following instruments and sources for gathering the information:

. An online survey in Google Forms that I ran on Facebook, Telegram, and via corporate Slack channel.
. Live interview with movie fans.
. Field research in the movie spot.
. Review and analysis of competitive apps like https://apps.apple.com/ua/app/%D0%BF%D0%BB%D0%B0%D0%BD%D0%B5%D1%82%D0%B0-%D0%BA%D1%96%D0%BD%D0%BE/id593841464?l=ru[Planeta Kino^], https://apps.apple.com/ua/app/fander/id1185465114[Fander^]. I gathered feedback from live conversations about the mentioned apps, and checked the feedback on the App Store.

=== 1. Online survey with Google Forms

I started my research of the target audience with an online survey. In this my friends, colleagues, fellow students and even people I don't really know were of great help. I spread my questionnaire through Facebook, Telegram, and Slack. I used Google Forms for gathering answers, and then - Excel file for results.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6aa73388525fb870fce_UYbecSSTNeXh7Fgts8d9TA67cV4cZOWV9yeDgmFgNkO7sre49QezHdWEUCVFx_YDphP2mZEHprkBRKQLbSU3ZOjcTTvQwpVap9B1tLgdY6fQBXKatoq28fpp7lcslSUTQbpDlCFE.png[]

==== *Questions in my online questionnaire:*

. Why do you usually go to the movies?
. What are your criteria for picking films? How do you buy tickets?
. What obstacles do you face while picking a film, buying and paying for a ticket?

=== 2. Live interview

For this stage I invited people I know and even those I don't really know but they're part of the design community. They agreed to participate after I shared the idea through the official Telegram channel of the design school where I studied.

==== *Questions for the interview:*

. Do you attend movies? If yes, then what are you searching for there? If the answer to the first question is no, then I ask 'Why is that?'
. How do you pick films and buy tickets?
. What obstacles do you face while picking a film, buying and paying for a ticket?
. How often do you use your smartphone for that?
. What apps do you usually use?

==== The outcome from a couple of talks:'

*Interviewee 1*

*Name:* Daniil

*Age:* 28

*How often does he go to the movies*

Daniil hasn't been to the movies since the beginning of the pandemic. Before the pandemic, he attended movies from time to time with his family and friends.

*Motivation*

He's driven by the opportunity to rest from work and experience positive emotions.&nbsp Daniil loves watching films on a big screen.

*How he picks movies and buys tickets*

He checks the title and the cover, reads the description, and watches
the trailer. The latter uncovers about 50% of the plot, Daniil says.Then, he considers the feedback from
the audience online. For picking films and purchasing tickets he goes with a https://apps.apple.com/us/app/%D0%B2%D0%BA%D0%B8%D0%BD%D0%BE-%D0%BF%D0%BE%D0%BA%D1%83%D0%BF%D0%BA%D0%B0-%D0%B1%D0%B8%D0%BB%D0%B5%D1%82%D0%BE%D0%B2-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD/id757872310[Vkino^] app.

*Suggestions on how to improve the service*

. Add locations of the movies to the app to ease the choice for visitors.
. Add maps to build a route from the visitor's locations to the movie place.
. Improve an online seats map to clearly show where the screen is.
. Connect the app to Apple and Google Pay to ease the purchase process.

*Interviewee 2*

*Name:* Sophia

*Age:* 35
*How often does she go to the movies*

Sophia never attended the movies since the pandemic, and she's not really a huge fan.

*Motivation*

Spending time with her dear people, especially with the nephew who loves cartoons. Sophia prefers
impressive special effects on a big screen and watching films right after the release.

*How she picks movies and buys tickets*

She checks the trailer on the movies' website or just somewhere on the Internet, then - buys tickets from the official website. Sophia generally finds it convenient unless they have troubles with the website (when it doesn't work for a few days). Then she books tickets through the phone and then purchases them at the movies. She doesn't use apps because that's her partner's prerogative.

*Suggestions on how to improve the service*

. Create one and only app that would give information about every single movie place in the city, also - allow booking and purchasing tickets.
. Make it possible to purchase tickets through Apple and Google Pay with no need to add users' data every time.
. Make fewer registration steps on the way to the purchase.
. Provide an opportunity to buy popcorn and sodas through the app and pick them up
at the movies with no queues (we could use a barcode or something like this for payment confirmation).

*Interviewee 3*

*Name:* Mariia

*Age:* 20

*How often does she go to the movies*

She's been to the movies a couple of times because of the pandemic. Before she used to go there monthly.

*Motivation*

It's a nice way to have fun and relax with friends.

*How she picks movies and buys tickets*

She usually checks the trailer, searches for ads about the film, and considers her friends' feedback. Before she used https://multiplex.ua/cinema/kharkiv/dafi
[Multiplex^] to pick a movie and purchase tickets as she used to live right next to this
movie place. Now she lives downtown and prefers the Planeta Kino&nbsp app. It provides a user-friendly
interface, a great variety of films, and an Apple pay payment method.

She's frustrated because it takes time and effort to switch seats when you book tickets online. After the choice is made, she has to wait for 15-20 minutes till her previous order gets canceled. And someone can book the seats she wants while she's waiting.

*Suggestions on how to improve the service* +
- Organise the catalogue of films the way we can see several options on one screen at once, this speeds up the search. Planeta Kino offers horizontal scrolling and shows just one film on a mobile screen.

- Offer an easy way to change the booked seats for other ones before the purchase.

=== 3. Field research

To feel the frustration users tend to feel while using apps, I communicated with them and tried myself in the
role of a user. I visited 2 movie places in my city, Planeta Kino and Multiplex. This way, I was able to
observe the visitors, their behavior in front of the checkout, the ticket purchase process, the cashier's
behavior, also the tech they're using to provide a better service.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6a95a35bad1845e403e_kdcxokWRD4f4YwSbFnLVZMI6DhlJPVz6eM_XM_bAZ6lJ5CUW0QlLoT9tCvayHYHmP5aojg8FXIKQCfuIAa-QFt-nwIWGPCEHRCoH5PGDNwaVdZ99HcCUKiE_JPrfwE0nLkTa0OjF.png[]

I also got myself involved in this process by becoming a customer, I put myself in their shoes,
and this helped me experience their journey. I started to understand the idea behind the communication with
users, how important it is to feel their frustration to come up with a better solution.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6a936aae43a296606d8_snSpiVfZFzG4i361ndi1l_ZguL_Ljjga4JRK_BV-6VEJnxjudeQRMoALL5bdN8sgs6PRUbEwLd2UYeVfwfNKUjd-JMojAfi1jS0Y6w9Zn7fCCrdW_eJQgM5n62VoSyfxmG-EYqxo.png[]

=== 4. Competitors review and analysis

We have many applications for buying movie tickets. And I have selected the most popular and frequently used ones for my analysis: https://apps.apple.com/ua/app/%D0%BF%D0%BB%D0%B0%D0%BD%D0%B5%D1%82%D0%B0-%D0%BA%D1%96%D0%BD%D0%BE/id593841464?l=ru[Planeta Kino^], https://apps.apple.com/ua/app/multiplex-cinema/id1160648734">[Multiplex^], and https://apps.apple.com/ua/app/fander/id1185465114">[Fander^].

I installed these applications on my iPhone SE to analyze and test how they look and work, find their advantages, disadvantages that need to be avoided and, of course, saturate my brain with ideas and inspiration. And at the same time, I analyze user reviews of the applications in the App Store.

In the next part I'll start working with the user personas for our future product, their goals, needs and problems based on the results that I got earlier from the real users.

==== *User profile and requirements:*

As a result of the research phase, we should collect data on the future users in the form of a persona. I
created a persona and listed her (his) frustration points, goals, and needs.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a77fb9eeb30b6f14a5ec83_vV0XF4GoC2Qqls_1uVSQFgliPGLPdK3IMexI32Sqso4JWIYlLLn0hkeqAIy0aAxE1ak6dt6I5Hk9s70gWaV64yg9L7-kAFnHze-ubhvgqK0Nq9MHnQZlEtR7IoOP8o7wCvXvCBzI.png[]

==== *Ideas generation and future product requirements:*

With the goal and needs of the target audience in mind I've generated ideas to cover each frustration point of the users.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6a955362ee89da12c03_x-zN6UprZkZmEQxxNKgFEmYr1FSR_GU8C3bNpcK1Nxc_SGNFJaK9qXdO_kfKB2jvtIi2cXm4sMXmcR_Wv2tNp0nFZscw-JQlFflIQG7EhJFL-GHb5PzEdEatgwu4O7sg2-OWrbVH.png[]

==== User story:

Designing a future product begins with the user story phase. At this stage, you need to describe the cases where the product will be used by different types of users. And that's what I did.

In the next part I'll be creating the user stories (scenarios) of the most common cases
of how users use the future product from the moment of opening the App till they achieve their goal.

*Story 1: Evening at the movies (Regular user)*

On the weekend, Alexander was thinking about how to spend the evening, somehow go out and have fun. He remembered that he had not visited the movies for a long time and decided to invite his best friend to go with him. Sure thing, the friend agreed
:-)

Alexander reached for his phone to find tickets online through the app. He checked the posters of
the movies playing that day, and the new Justice League caught his eye. He watched the trailer, checked the
movie story, and decided to go for it. He chose a movie place that was closest and a suitable session, picked
seats for two, and paid for the tickets. Then, he checked the tickets', added them to 'Wallet' for quick and
easy access, and closed the app. Finally, time to get ready for the show!

After a while, Alexander and his friend met at the movies and joined the line to enter the movie hall. Alexander prepared the tickets for scanning in the "Wallet". After the check, they took their seats and started watching the movie. BTW, it was a good piece. And Alexander gave it 5 out of 5 when received a request for evaluation from the App.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6a911df140606adf18c_imMiWE1xIzeGdSFzm1CPQPayrn8ceU50kA1bQJUR3CMJBTVT5Gr5CxGiayB98irnxNgFmtFF97YwYD3LpH3igUNQLSbbRYo5RhGDM1f8vZs5g4tahQcAv83E4CxS2Ln7kKbunuQ7.png[]

*Story 2: Movie premiere (New user)*

It was a usual working day. Alexander was on a lunch break, discussing the upcoming Justice League, which had been added to the future release at the movies. Everyone was looking forward to seeing it. The only way to get tickets for the premiere was to pre-order them online. He picked up his phone, downloaded the application, opened it, skipped the registration, and in no time found the movie he was seeking. He selected the movie place, session, and seats.
Before he had a chance to pay for the tickets, the App asked for mandatory registration to complete the
purchase. He's registered in one tap with his Apple account. After the registration, he paid for the tickets,
checked the ticket details, and closed the application.

In three weeks, on the movie premiere day, Alexander and his friend met at the movies and stood in line in front of the entrance to the movie hall. Alexander opened the application, went to the 'Tickets' section, and prepared the tickets for scanning.

After check-in, they entered the movie hall, took their seats, and started watching the movie. Alexander
liked the movie very much. After watching, he received a notification from the App asking him to rate the
movie. He gave it 5 out of 5.

image::https://uploads-ssl.webflow.com/5c4c30d0c49ea6746fafc90c/60a4c6aa2ddd2a47f40867ee_g3031GOYJKO7VaBSO0UM0lTYz7eKOZKpON4rEWo3VO54gWbUOuG0tJfHbtREnLP5vqWdJmC_3GQl6r0cOC15y1oRuQC2GZ-i8QeThcRlirAHQNG8ZZKrIgEnqWLPbMZIm9oQblvi.png[]

== What *I realized as I finished this stage*

The first thing that came to my mind before starting this course is that it is complicated: how I will do it, it takes time, it's difficult, etc. But as soon as the education started and I started delving into these processes, I realized that no successful product was made based on the business owners', designers', or developers' wishes. They're all based on users' needs. I got not just an experience of a lifetime creating products for users, but also had a lot of fun in the journey!

== Tools *applied*

. I used https://apps.apple.com/us/app/xmind-mind-map/id1286983622[Xmind^] to create the mind
mapping and the functional structure, it's a very handy app for UX designers, simple and easy to use.
. I used https://www.figma.com/[Figma^] to create the user flow (scenarios), wireframes, and
of course the interface UI. It's one of the greatest prototyping tools which is primarily web-based,
with additional offline features enabled by desktop applications for macOS and Windows.





